### ISSUE TITLE
it is detect floor and table surface

### ISSUE THREAD

**Issue by vishalvanpariya** [kboy-silvergym/ARCore-Kotlin-Sampler#5]
I am trying to detect only table surface but this is detected Floor and table surface give some solution related to it.
Give me some idea for differentiate it. 
Thank you

**Comment by kboy-silvergym** [comment]
@vishalvanpariya 
Sorry, you can't differentiate it by ARCore's plane detection.
If you want, you should place a marker image on the table and detect it as a AR marker.
